### ISSUE TITLE
server pulled

### ISSUE THREAD

**Issue by laramie14** [yellows8/ninupdates#1]
Is there any way to host the downloads we already have to a server Nintendo can't touch? Or even make a local server?

**Comment by yellows8** [comment]
I'm not sure what you're asking. Not sure what the point of a "local server" is either, unless it's for 3DS or something...

**Comment by laramie14** [comment]
Yeah, it'd be for me to have the updates on my computer and get the soap
server to connect to my local IP and direct it to where my files are for me
to download or if I place the files on my server, how would I get it to
where anyone could get the cia's I have for downloading and updating their
3ds's?

**Comment by yellows8** [comment]
"soap server to connect to my local IP" That makes no sense. "anyone could ..." Sounds like you want to publicly share copyrighted content...

**Comment by laramie14** [comment]
No it's not that, I just want to find a way or make a way to allow users to
still use things like 3dsnus to update their 3ds's since Nintendo pulled
their server. And I thought, well if everyone had their own downloads of
the firmware, then they could update from the firmwares they have. Like for
example, I have a 8.1 JPN n3ds, and can't use ninjhax to update to 9.0.0-20
which I have the cias for. So I was going to use ntr to update to 9.0.0-20
however it uses the server that Nintendo pulled. I already had the cia's
just in case from awhile back, but now I can't update.

**Comment by yellows8** [comment]
No server was ever "pulled".

Anyway, hosting your own local CDN is trivial _if_ the tmd for the title is still available on the official CDN(or you could patch NIM module to use plain http for that too). Just use the same URL structure as the actual CDN.

**Comment by laramie14** [comment]
Hmm okay, also if the sever wasn't "pulled" then why won't 3dsnus obtain
the files anymore? Just trying to expand my knowledge ^_^

**Comment by yellows8** [comment]
Because certain title-versions are not longer available, duh.

**Comment by laramie14** [comment]
That's totally it haha okay thanks ^_^
