### ISSUE TITLE
3DS Title List Broken in FW 10.0.0-27

### ISSUE THREAD

**Issue by ghost** [yellows8/ninupdates#2]
FW 10.0.0-27 has been released for the 3DS.
However It has been added in older version from 9.x to Title List.
For example TitleID 0004001000021900 (eShop USA) has been written in this way.

| 0004001000021900
| USA
| <B>[[10.0.0-27 | v13321]]</B>, [[9.0.0-20 (stage2) | v15366]], [[9.3.0-21 (stage2) | v16384]], [[9.5.0-22 | v17422]], [[9.6.0-24 | v18432]], [[9.7.0-25 | v19465]]

That's correct.
| 0004001000021900
| USA
| [[9.0.0-20 (stage2) | v13321]], [[9.3.0-21 (stage2) | v15366]], [[9.5.0-22 | v16384]], [[9.6.0-24 | v17422]], [[9.7.0-25 | v18432]], <B>[[10.0.0-27 | v19465]]</B>

**Comment by yellows8** [comment]
12cfcc45adba53e022b8e20aa158e7e13ff2fd2e
