### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [yellows8/ninupdates#4]
What is the license of this project? Are we able to host our own?

**Comment by yellows8** [comment]
Public-domain I guess. You can attempt the latter I guess if you can even get that far.

**Comment by ghost** [comment]
I am currently hosting my own but it's private. I was just wondering if I could make it public. I'm not going to announce it or anything I'm just going to remove HTTP Authentication.

Should you or I add a LICENSE file so that other people don't ask the same question? I recommend http://unlicense.org/ if you are planning on public-domain

**Comment by yellows8** [comment]
"I was just wondering if I could make it public." "{licensing}"

I don't care much tbh.

**Comment by ghost** [comment]
Ok, thanks. I'll make sure to give proper credit to you.
